[package]
name = "rustlog"
version = "0.1.0"
edition = "2021"
description = "Rust language experimental playground."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "^0.3"
rand = "^0.8"
