[package]
name = "rustlog"
version = "0.1.0"
edition = "2021"
description = "Rust language experimental playground."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hello"
path = "src/bin/hello/main.rs"

[[bin]]
name = "guess"
path = "src/bin/guess/main.rs"

[dependencies]
time = { version = "^0.3", features = ["local-offset"] }
rand = "^0.8"
utf8_slice = "1.0.0"
twox-hash = "^1.6"
