{
 "title": "Rust Axum Example Metrics Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{container=\"user-container\", pod=~\"prometheus-metrics-example-.*\"}[5m])) by (container) /sum(increase(container_cpu_cfs_periods_total{container=\"user-container\", pod=~\"prometheus-metrics-example-.*\"}[5m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"prometheus-metrics-.*\", container=\"user-container\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_microseconds_bucket[5m])) by (le, pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "rate(http_request_total[5m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_total{pod=~\"prometheus-metrics-example-.*\", container=\"user-container\", status=~\"2..\"}[5m])) by (pod) \n/ \nsum(rate(http_request_total{pod=~\"prometheus-metrics-example-.*\", container=\"user-container\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}