apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics-example
  namespace: default
  labels:
    app.kubernetes.io/name: web-apps
    app.kubernetes.io/component: prometheus-metrics-example
spec:
  selector:
    app.kubernetes.io/name: web-apps
    app.kubernetes.io/component: prometheus-metrics-example
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: http
    nodePort: 30300
  - name: metrics
    protocol: TCP
    port: 3001
    targetPort: metrics
    nodePort: 30301

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-metrics-example
  namespace: default
  labels:
    app.kubernetes.io/name: web-apps
    app.kubernetes.io/component: prometheus-metrics-example
    app.kubernetes.io/version: v0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-apps
      app.kubernetes.io/component: prometheus-metrics-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-apps
        app.kubernetes.io/component: prometheus-metrics-example
        app.kubernetes.io/version: v0.1
    spec:
      imagePullSecrets:
      - name: coding
      containers:
      - name: user-container
        image: cartcart-docker.pkg.coding.net/rustlog/web_apps/prometheus_metrics_example:v0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: false
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add: []
            drop: ["ALL"]
          seccompProfile: 
            type: RuntimeDefault
        ports:
        - name: http
          containerPort: 3000
        - name: metrics
          containerPort: 3001

---

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prometheus-metrics-example
  namespace: monitoring
  labels:
    release: monitoring
    app.kubernetes.io/name: web-apps
    app.kubernetes.io/component: prometheus-metrics-example
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus-metrics-example
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
