[package]
name = "optional-dependency"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "^1.0", features = ["derive"], optional = true }
serde_json = "^1.0"

[features]
serde = ["dep:serde"]
