name: Rust

on:
  pull_request:
    branches:
      - main  # or specify the branch you want to trigger the action on
  merge_group:
    types: [checks_requested]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run tests
        run: cargo test --verbose
